In [9]:
import pandas as pd

file_path = "../data/raw/OXYGPRPPAU_TransactionReport_2025-05-12_to_2025-05-18.csv"

df = pd.read_csv(
    file_path,
    sep="|",
    skiprows=2
)

df.head()
df.shape
df.columns.tolist()
df.dtypes

Txn Date                   str
Corporate Name             str
Proxy Card Number        int64
Card Number                str
RRN                    float64
Auth Code              float64
Ext Txn Id                 str
Amount                 float64
TransactionType            str
Status                     str
Customer Id              int64
Post Wallet Balance    float64
CR/DR Flag                 str
Other Party Id             str
Other Party Name           str
Currency                 int64
Product                    str
Txn Amount             float64
Fees                   float64
Description                str
mcc                    float64
ActivationDate             str
dtype: object

In [10]:
df["TransactionType"].value_counts()

TransactionType
POS                            8715
LOAD                           3885
ATM                            1240
ECOM                            813
ATM_BALANCE_ENQUIRY             122
CARD_TO_CARD                     80
ATM_INSUFF_DECLINE_FEE           56
ATM_INVALID_PIN_DECLINE_FEE      49
REFUND                           21
ECOM_REVERSAL                    15
POS_REVERSAL                     13
ATM_REVERSAL                     12
FUNDPOST_CREDIT                   8
FUNDPOST_DEBIT                    4
LOAD_REVERSAL                     1
Name: count, dtype: int64

In [11]:
df["Status"].value_counts()

Status
PAYMENT_SUCCESS    14995
REVERSED              39
Name: count, dtype: int64

In [12]:
df.isnull().sum().sort_values(ascending=False)

Description            11042
mcc                     3992
Auth Code               3980
RRN                     3966
Other Party Id            15
Other Party Name          14
Proxy Card Number          0
Card Number                0
Txn Date                   0
Corporate Name             0
Status                     0
Ext Txn Id                 0
TransactionType            0
Amount                     0
CR/DR Flag                 0
Post Wallet Balance        0
Customer Id                0
Currency                   0
Txn Amount                 0
Product                    0
Fees                       0
ActivationDate             0
dtype: int64

In [13]:
df["Amount"].describe()

count    15034.000000
mean       184.088857
std        437.261245
min          0.010000
25%          8.300000
50%         38.455000
75%        166.200000
max      17328.640000
Name: Amount, dtype: float64

In [14]:
df["Amount"].max()

np.float64(17328.64)

In [15]:
df["Amount"].min()

np.float64(0.01)

In [16]:
df["Amount"].mean()

np.float64(184.08885683118265)

In [17]:
df["Txn Date"] = pd.to_datetime(df["Txn Date"])

In [18]:
df["Txn Date"].dtype

dtype('<M8[us]')

In [19]:
df["Txn Date"].min()
df["Txn Date"].max()

Timestamp('2025-05-18 23:57:23')

In [23]:
load_transactions = df[df["TransactionType"] == "LOAD"]

In [24]:
df["TransactionType"] == "LOAD"

0        False
1        False
2        False
3        False
4        False
         ...
15029    False
15030    False
15031    False
15032    False
15033    False
Name: TransactionType, Length: 15034, dtype: bool

In [26]:
high_value_loads = load_transactions[
    load_transactions["Amount"] > 5000
]

In [27]:
high_value_loads.head()

,Txn Date,Corporate Name,Proxy Card Number,Card Number,RRN,Auth Code,Ext Txn Id,Amount,TransactionType,Status,...,CR/DR Flag,Other Party Id,Other Party Name,Currency,Product,Txn Amount,Fees,Description,mcc,ActivationDate
1729,2025-05-18 02:23:18,RL4YRGMCABSATM,7100000860,4424XXXXXXXX8600,NaN,NaN,7332598875357191,10155.39,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,10155.39,0.0,Autopay,NaN,2024-11-07
1897,2025-05-18 01:53:32,RL4YRGMCABSATM,7100000802,4424XXXXXXXX8022,NaN,NaN,5866514063476383,6107.75,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,6107.75,0.0,Autopay,NaN,2025-01-23
8070,2025-05-15 02:22:12,RL4YRGMCABSATM,7100000911,4424XXXXXXXX9111,NaN,NaN,9802292179050181,6140.32,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,6140.32,0.0,Autopay,NaN,2024-11-20
9446,2025-05-14 10:31:11,RL4YRGMCABSATM,7100003207,4424XXXXXXXX2071,NaN,NaN,5093773673058566,17328.64,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,17328.64,0.0,Transferring funds from old account,NaN,2025-05-14
12699,2025-05-13 01:37:37,RL4YRGMCABSATM,7100001762,4424XXXXXXXX7627,NaN,NaN,3607491529381635,6543.01,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,6543.01,0.0,Autopay,NaN,2024-11-07

In [28]:
df["TransactionType"].value_counts()

TransactionType
POS                            8715
LOAD                           3885
ATM                            1240
ECOM                            813
ATM_BALANCE_ENQUIRY             122
CARD_TO_CARD                     80
ATM_INSUFF_DECLINE_FEE           56
ATM_INVALID_PIN_DECLINE_FEE      49
REFUND                           21
ECOM_REVERSAL                    15
POS_REVERSAL                     13
ATM_REVERSAL                     12
FUNDPOST_CREDIT                   8
FUNDPOST_DEBIT                    4
LOAD_REVERSAL                     1
Name: count, dtype: int64

In [29]:
df["Status"].value_counts()

Status
PAYMENT_SUCCESS    14995
REVERSED              39
Name: count, dtype: int64

In [30]:
df.isnull().sum().sort_values(ascending=False)

Description            11042
mcc                     3992
Auth Code               3980
RRN                     3966
Other Party Id            15
Other Party Name          14
Proxy Card Number          0
Card Number                0
Txn Date                   0
Corporate Name             0
Status                     0
Ext Txn Id                 0
TransactionType            0
Amount                     0
CR/DR Flag                 0
Post Wallet Balance        0
Customer Id                0
Currency                   0
Txn Amount                 0
Product                    0
Fees                       0
ActivationDate             0
dtype: int64

In [31]:
df["Amount"].describe()

count    15034.000000
mean       184.088857
std        437.261245
min          0.010000
25%          8.300000
50%         38.455000
75%        166.200000
max      17328.640000
Name: Amount, dtype: float64

In [32]:
df["Txn Date"] = pd.to_datetime(df["Txn Date"])

In [33]:
df["Txn Date"].dtype

dtype('<M8[us]')

In [34]:
df["Customer Id"].nunique()

1352

In [35]:
df["Card Number"].nunique()

1357

In [36]:
df["Other Party Id"].nunique()

3832

In [37]:
df["TransactionType"].value_counts().sort_index()

TransactionType
ATM                            1240
ATM_BALANCE_ENQUIRY             122
ATM_INSUFF_DECLINE_FEE           56
ATM_INVALID_PIN_DECLINE_FEE      49
ATM_REVERSAL                     12
CARD_TO_CARD                     80
ECOM                            813
ECOM_REVERSAL                    15
FUNDPOST_CREDIT                   8
FUNDPOST_DEBIT                    4
LOAD                           3885
LOAD_REVERSAL                     1
POS                            8715
POS_REVERSAL                     13
REFUND                           21
Name: count, dtype: int64

In [38]:
df["mcc"].nunique()

136

In [39]:
df["mcc"].isna().sum()

np.int64(3992)

In [40]:
df["mcc"].value_counts().head(20)

mcc
5541.0    2159
6011.0    1479
7523.0    1354
5411.0    1298
5812.0    1225
5814.0     966
4784.0     342
5499.0     335
5310.0     148
5921.0     142
4121.0     134
5912.0     121
7542.0      89
9399.0      79
5462.0      63
5813.0      61
5999.0      50
5200.0      44
4814.0      42
5943.0      42
Name: count, dtype: int64

In [41]:
load_transactions = df[
    df["TransactionType"] == "LOAD"
]

In [42]:
load_transactions.shape

(3885, 22)

In [43]:
high_value_loads = load_transactions[
    load_transactions["Amount"] > 5000
]

In [44]:
high_value_loads.shape

(6, 22)

In [45]:
high_value_loads.head()

,Txn Date,Corporate Name,Proxy Card Number,Card Number,RRN,Auth Code,Ext Txn Id,Amount,TransactionType,Status,...,CR/DR Flag,Other Party Id,Other Party Name,Currency,Product,Txn Amount,Fees,Description,mcc,ActivationDate
1729,2025-05-18 02:23:18,RL4YRGMCABSATM,7100000860,4424XXXXXXXX8600,NaN,NaN,7332598875357191,10155.39,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,10155.39,0.0,Autopay,NaN,2024-11-07
1897,2025-05-18 01:53:32,RL4YRGMCABSATM,7100000802,4424XXXXXXXX8022,NaN,NaN,5866514063476383,6107.75,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,6107.75,0.0,Autopay,NaN,2025-01-23
8070,2025-05-15 02:22:12,RL4YRGMCABSATM,7100000911,4424XXXXXXXX9111,NaN,NaN,9802292179050181,6140.32,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,6140.32,0.0,Autopay,NaN,2024-11-20
9446,2025-05-14 10:31:11,RL4YRGMCABSATM,7100003207,4424XXXXXXXX2071,NaN,NaN,5093773673058566,17328.64,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,17328.64,0.0,Transferring funds from old account,NaN,2025-05-14
12699,2025-05-13 01:37:37,RL4YRGMCABSATM,7100001762,4424XXXXXXXX7627,NaN,NaN,3607491529381635,6543.01,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,6543.01,0.0,Autopay,NaN,2024-11-07

In [46]:
load_transactions = df[
    df["TransactionType"] == "LOAD"
]

In [47]:
high_value_loads = load_transactions[
    load_transactions["Amount"] > 5000
]

In [48]:
df["Customer Id"].nunique()

1352

In [49]:
df["Card Number"].nunique()

1357

In [50]:
df["Currency"].value_counts(dropna=False)

Currency
36    15034
Name: count, dtype: int64

In [51]:
df["mcc"].nunique()

136

In [52]:
df["mcc"].isna().sum()

np.int64(3992)

In [53]:
load_transactions = df[df["TransactionType"] == "LOAD"]

high_value_loads = load_transactions[
    load_transactions["Amount"] > 5000
]

high_value_loads.shape

(6, 22)

In [54]:
high_value_loads

,Txn Date,Corporate Name,Proxy Card Number,Card Number,RRN,Auth Code,Ext Txn Id,Amount,TransactionType,Status,...,CR/DR Flag,Other Party Id,Other Party Name,Currency,Product,Txn Amount,Fees,Description,mcc,ActivationDate
1729,2025-05-18 02:23:18,RL4YRGMCABSATM,7100000860,4424XXXXXXXX8600,NaN,NaN,7332598875357191,10155.39,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,10155.39,0.0,Autopay,NaN,2024-11-07
1897,2025-05-18 01:53:32,RL4YRGMCABSATM,7100000802,4424XXXXXXXX8022,NaN,NaN,5866514063476383,6107.75,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,6107.75,0.0,Autopay,NaN,2025-01-23
8070,2025-05-15 02:22:12,RL4YRGMCABSATM,7100000911,4424XXXXXXXX9111,NaN,NaN,9802292179050181,6140.32,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,6140.32,0.0,Autopay,NaN,2024-11-20
9446,2025-05-14 10:31:11,RL4YRGMCABSATM,7100003207,4424XXXXXXXX2071,NaN,NaN,5093773673058566,17328.64,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,17328.64,0.0,Transferring funds from old account,NaN,2025-05-14
12699,2025-05-13 01:37:37,RL4YRGMCABSATM,7100001762,4424XXXXXXXX7627,NaN,NaN,3607491529381635,6543.01,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,6543.01,0.0,Autopay,NaN,2024-11-07
14980,2025-05-12 01:34:32,RL4YRGMCABSATM,7100002253,4424XXXXXXXX2536,NaN,NaN,6673769969532866,6906.23,LOAD,PAYMENT_SUCCESS,...,CR,OXYGPRPPAU,M2P Business,36,GENERAL,6906.23,0.0,Autopay,NaN,2025-01-06

In [55]:
high_value_loads[
    ["Txn Date", "Card Number", "Customer Id", "Amount", "TransactionType", "Status"]
]

,Txn Date,Card Number,Customer Id,Amount,TransactionType,Status
1729,2025-05-18 02:23:18,4424XXXXXXXX8600,8616590912665064,10155.39,LOAD,PAYMENT_SUCCESS
1897,2025-05-18 01:53:32,4424XXXXXXXX8022,4251556492707721,6107.75,LOAD,PAYMENT_SUCCESS
8070,2025-05-15 02:22:12,4424XXXXXXXX9111,8977973134289625,6140.32,LOAD,PAYMENT_SUCCESS
9446,2025-05-14 10:31:11,4424XXXXXXXX2071,3046161171508648,17328.64,LOAD,PAYMENT_SUCCESS
12699,2025-05-13 01:37:37,4424XXXXXXXX7627,2550969752248452,6543.01,LOAD,PAYMENT_SUCCESS
14980,2025-05-12 01:34:32,4424XXXXXXXX2536,6095710042248108,6906.23,LOAD,PAYMENT_SUCCESS

In [56]:
high_value_loads = load_transactions[
    load_transactions["Amount"] > 5000
]

In [57]:
def check_high_value_loads(df, threshold):
    ...

In [58]:
check_high_value_loads(df, 5000)

In [59]:
check_high_value_loads(df, 7000)

In [60]:
high_value_loads[
    ["Txn Date", "Card Number", "Customer Id", "Amount", "TransactionType", "Status"]
]

,Txn Date,Card Number,Customer Id,Amount,TransactionType,Status
1729,2025-05-18 02:23:18,4424XXXXXXXX8600,8616590912665064,10155.39,LOAD,PAYMENT_SUCCESS
1897,2025-05-18 01:53:32,4424XXXXXXXX8022,4251556492707721,6107.75,LOAD,PAYMENT_SUCCESS
8070,2025-05-15 02:22:12,4424XXXXXXXX9111,8977973134289625,6140.32,LOAD,PAYMENT_SUCCESS
9446,2025-05-14 10:31:11,4424XXXXXXXX2071,3046161171508648,17328.64,LOAD,PAYMENT_SUCCESS
12699,2025-05-13 01:37:37,4424XXXXXXXX7627,2550969752248452,6543.01,LOAD,PAYMENT_SUCCESS
14980,2025-05-12 01:34:32,4424XXXXXXXX2536,6095710042248108,6906.23,LOAD,PAYMENT_SUCCESS

In [ ]:
high_value_loads[
    ["Txn Date", "Card Number", "Customer Id", "Amount", "TransactionType", "Status"]
]

,Txn Date,Card Number,Customer Id,Amount,TransactionType,Status
1729,2025-05-18 02:23:18,4424XXXXXXXX8600,8616590912665064,10155.39,LOAD,PAYMENT_SUCCESS
1897,2025-05-18 01:53:32,4424XXXXXXXX8022,4251556492707721,6107.75,LOAD,PAYMENT_SUCCESS
8070,2025-05-15 02:22:12,4424XXXXXXXX9111,8977973134289625,6140.32,LOAD,PAYMENT_SUCCESS
9446,2025-05-14 10:31:11,4424XXXXXXXX2071,3046161171508648,17328.64,LOAD,PAYMENT_SUCCESS
12699,2025-05-13 01:37:37,4424XXXXXXXX7627,2550969752248452,6543.01,LOAD,PAYMENT_SUCCESS
14980,2025-05-12 01:34:32,4424XXXXXXXX2536,6095710042248108,6906.23,LOAD,PAYMENT_SUCCESS